# Generated by Django 5.1.6 on 2025-08-29 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=50, unique=True)),
                ('jabatan', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('tanggal_masuk', models.DateField()),
                ('alamat', models.TextField()),
                ('no_telp', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='guru/')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nisn', models.CharField(max_length=20, unique=True)),
                ('nomor_induk', models.CharField(max_length=20, unique=True)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('agama', models.CharField(blank=True, max_length=30, null=True)),
                ('nama_ayah', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_ibu', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='siswa/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('guru', 'Guru'), ('kepala', 'Kepala Sekolah')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LaporanPerkembangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('siap', 'Siap'), ('belum', 'Belum')], max_length=10)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=10)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siswa')),
            ],
        ),
    ]
