# Generated by Django 5.1.6 on 2025-08-29 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Alpa', 'Tanpa Keterangan'), ('Libur', 'Libur')], max_length=20)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siswa')),
            ],
            options={
                'unique_together': {('siswa', 'tanggal')},
            },
        ),
    ]
