# Generated by Django 5.1.6 on 2025-08-30 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_absensi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('mulai', models.DateField(blank=True, null=True)),
                ('selesai', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='laporanperkembangan',
            name='agama_budi_pekerti',
            field=models.TextField(blank=True, null=True, verbose_name='Agama dan Budi Pekerti'),
        ),
        migrations.AddField(
            model_name='laporanperkembangan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laporanperkembangan',
            name='foto_kegiatan',
            field=models.ImageField(blank=True, null=True, upload_to='laporan_foto/'),
        ),
        migrations.AddField(
            model_name='laporanperkembangan',
            name='jati_diri',
            field=models.TextField(blank=True, null=True, verbose_name='Jati Diri'),
        ),
        migrations.AddField(
            model_name='laporanperkembangan',
            name='literasi',
            field=models.TextField(blank=True, null=True, verbose_name='Dasar Literasi'),
        ),
        migrations.AddField(
            model_name='laporanperkembangan',
            name='projek_penguatan_pancasila',
            field=models.TextField(blank=True, null=True, verbose_name='Projek Penguatan Profil Pancasila'),
        ),
        migrations.AddField(
            model_name='laporanperkembangan',
            name='sains_teknologi_seni_matematika',
            field=models.TextField(blank=True, null=True, verbose_name='Sains, Teknologi, Rekayasa, Seni, dan Matematika'),
        ),
    ]
