# Generated by Django 5.1.6 on 2025-08-30 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tahunajaran_laporanperkembangan_agama_budi_pekerti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporanperkembangan',
            name='agama_budi_pekerti',
        ),
        migrations.RemoveField(
            model_name='laporanperkembangan',
            name='foto_kegiatan',
        ),
        migrations.RemoveField(
            model_name='laporanperkembangan',
            name='jati_diri',
        ),
        migrations.RemoveField(
            model_name='laporanperkembangan',
            name='literasi',
        ),
        migrations.RemoveField(
            model_name='laporanperkembangan',
            name='projek_penguatan_pancasila',
        ),
        migrations.RemoveField(
            model_name='laporanperkembangan',
            name='sains_teknologi_seni_matematika',
        ),
        migrations.AlterField(
            model_name='laporanperkembangan',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='LaporanAspek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aspek', models.CharField(choices=[('agama_budi_pekerti', 'Agama & Budi Pekerti'), ('jati_diri', 'Jati Diri'), ('literasi', 'Dasar Literasi'), ('sains_teknologi_seni_matematika', 'Sains, Teknologi, Seni & Matematika'), ('projek_penguatan_pancasila', 'Projek Penguatan Profil Pancasila')], max_length=50)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='laporan_foto/')),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspek', to='main.laporanperkembangan')),
            ],
        ),
    ]
