# Generated by Django 5.1.6 on 2025-09-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_laporanperkembangan_agama_budi_pekerti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='status',
            field=models.CharField(choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Alpa', 'Tanpa Keterangan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='guru',
            name='jabatan',
            field=models.CharField(choices=[('kepala_sekolah', 'Kepala Sekolah'), ('tata_usaha', 'Tata Usaha'), ('wali_kelas', 'Wali Kelas'), ('guru', 'Guru')], max_length=20),
        ),
    ]
