# Generated by Django 5.1.6 on 2025-09-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_absensi_status_alter_guru_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tahunajaran'),
        ),
    ]
