# Generated by Django 5.1.6 on 2025-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_guru_tahun_ajaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='jabatan',
            field=models.CharField(choices=[('kepala_sekolah', 'Kepala Sekolah'), ('tata_usaha', 'Tata Usaha'), ('wali_kelas', 'Wali Kelas'), ('guru', 'Guru'), ('pengawas_tk', 'Pengawas TK'), ('komite_sekolah', 'Komite Sekolah')], max_length=20),
        ),
    ]
