# Generated by Django 5.1.6 on 2025-09-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_guru_jabatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='nip',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
