# Generated by Django 5.1.6 on 2025-09-20 15:01

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_guru_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.guru_upload_path),
        ),
        migrations.AlterField(
            model_name='laporanaspek',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.laporan_aspek_upload_path),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.siswa_upload_path),
        ),
    ]
