# Generated by Django 5.1.6 on 2025-09-23 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_guru_foto_alter_laporanaspek_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspekPerkembangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan untuk ditampilkan')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.RemoveField(
            model_name='laporanaspek',
            name='nama_aspek',
        ),
        migrations.AddField(
            model_name='laporanaspek',
            name='aspek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.aspekperkembangan'),
        ),
    ]
