# Generated by Django 5.1.6 on 2025-09-23 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aspekperkembangan_remove_laporanaspek_nama_aspek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporanaspek',
            name='aspek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.aspekperkembangan'),
        ),
    ]
