# Generated by Django 5.1.6 on 2025-09-30 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kelas'),
        ),
    ]
