# Generated by Django 5.1.6 on 2025-09-30 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='wali_kelas',
            field=models.ForeignKey(blank=True, limit_choices_to={'jabatan': 'wali_kelas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.guru'),
        ),
    ]
