# Generated by Django 5.2.6 on 2025-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_guru_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporanperkembangan',
            name='refleksi_orang_tua',
            field=models.TextField(blank=True, null=True),
        ),
    ]
