# Generated by Django 5.2.6 on 2025-10-02 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_tahunajaran_refleksi_semester_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tahunajaran',
            name='refleksi_semester_1',
        ),
        migrations.RemoveField(
            model_name='tahunajaran',
            name='refleksi_semester_2',
        ),
    ]
