# Generated by Django 5.2.6 on 2025-10-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_tahunajaran_refleksi_semester_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefleksiKomentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
