# Generated by Django 5.2.6 on 2025-10-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_refleksikomentar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefleksiKomentar',
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='refleksi_semester_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='refleksi_semester_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
