# Generated by Django 5.2.6 on 2025-10-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_refleksikomentar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tahunajaran',
            name='refleksi_semester_1',
        ),
        migrations.RemoveField(
            model_name='tahunajaran',
            name='refleksi_semester_2',
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='refleksi_global',
            field=models.TextField(blank=True, null=True),
        ),
    ]
