# Generated by Django 5.2.6 on 2025-10-02 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_tahunajaran_refleksi_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tahunajaran',
            name='refleksi_global',
        ),
        migrations.CreateModel(
            name='RefleksiKomentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tahunajaran')),
            ],
        ),
    ]
