# Generated by Django 5.2.6 on 2025-10-02 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_tahunajaran_refleksi_global_refleksikomentar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefleksiKomentar',
        ),
    ]
