# Generated by Django 5.2.6 on 2025-10-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_tahunajaran_refleksi_global'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tahunajaran',
            name='refleksi_global',
        ),
    ]
