# Generated by Django 5.2.6 on 2025-10-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_tahunajaran_refleksi_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='refleksikomentar',
            name='refleksi_global',
            field=models.TextField(blank=True, null=True),
        ),
    ]
