# Generated by Django 5.1.6 on 2025-10-03 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_refleksikomentar_refleksi_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspekperkembangan',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aspek_perkembangan', to='main.tahunajaran'),
        ),
    ]
