# Generated by Gemini

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_aspekperkembangan_tahun_ajaran'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspekperkembangan',
            old_name='nama',
            new_name='nama_aspek',
        ),
        migrations.RemoveField(
            model_name='aspekperkembangan',
            name='urutan',
        ),
        migrations.AddField(
            model_name='aspekperkembangan',
            name='deskripsi',
            field=models.TextField(default=''),
        ),
    ]
