# Generated by Django 5.1.6 on 2025-10-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_manual_schema_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspekperkembangan',
            options={},
        ),
        migrations.AlterField(
            model_name='aspekperkembangan',
            name='nama_aspek',
            field=models.CharField(max_length=100),
        ),
    ]
